# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee61b154cbed66559d35d22b207eaf218c3cf7b9b05391fe1323ece16aeeb8173061c6fa7b7122068a898573ef3c35aaed572c77821d5cfe72673605db7fe8fc

test:
  secret_key_base: 2da577bf179226cf4e8ec4832317dbd6ce68745003018ddffc1656bc023315c52863dc098adf7066e3e7381fdae3f4dc104b16901ed61cc4367f05fd51822324

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
